/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CancelOrderPage.java
 *
 * Created on Jul 7, 2009, 1:44:06 PM
 */

package com.omnesys.testnestq.gui;

import com.omnesys.nestq.classes.NestControl;
import java.awt.Color;

/**
 *
 * @author Pankaj
 */
public class CancelOrderPage extends javax.swing.JFrame implements Runnable
{
    private NestControl nc;

    /** Creates new form CancelOrderPage */
    public CancelOrderPage() {
        nc = HomePage.nc;
        init();
    }

    public void init()
    {
        initComponents();
        jLabel3.setForeground(Color.RED);
        java.awt.EventQueue.invokeLater(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NONJTextField1 = new javax.swing.JTextField();
        GUIOIJTextField2 = new javax.swing.JTextField();
        GUIOOIDJTextField3 = new javax.swing.JTextField();
        OKJButton1 = new javax.swing.JButton();
        CancelJButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel1.setText("Cancel Order");

        jLabel2.setText("Nest Order No                GUI Order ID                             GUI Original Order ID");

        OKJButton1.setText("OK");
        OKJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKJButton1ActionPerformed(evt);
            }
        });

        CancelJButton2.setText("Cancel");
        CancelJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelJButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("UserId");

        UserId.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NONJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(OKJButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CancelJButton2))
                                    .addComponent(GUIOIJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(GUIOOIDJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserId, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NONJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GUIOIJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GUIOOIDJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelJButton2)
                    .addComponent(OKJButton1))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKJButton1ActionPerformed
        System.out.println("request to cancel order placed");
        int flag = 0;
        if(NONJTextField1.getText() == null ||
           NONJTextField1.getText().length() == 0)
            flag++;
        if(GUIOIJTextField2.getText() == null ||
           GUIOIJTextField2.getText().length() == 0)
            flag++;
        if(GUIOOIDJTextField3.getText() == null ||
           GUIOOIDJTextField3.getText().length() == 0)
            flag++;
         if(UserId.getText() == null ||
           UserId.getText().length() == 0)
            flag++;
        if(flag < 4)
        nc.CancelOrder(this, NONJTextField1.getText(),
                             GUIOIJTextField2.getText(),
                             GUIOOIDJTextField3.getText(),UserId.getText());
        else
            jLabel3.setText("Atleast one of the fields must be filled");
}//GEN-LAST:event_OKJButton1ActionPerformed

    private void CancelJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelJButton2ActionPerformed
        this.setVisible(false);
        NONJTextField1.setText("");
        GUIOIJTextField2.setText("");
        GUIOOIDJTextField3.setText("");
    }//GEN-LAST:event_CancelJButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelOrderPage().setVisible(true);
            }
        });
    }*/
    public void run() {
                this.setVisible(true);
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelJButton2;
    private javax.swing.JTextField GUIOIJTextField2;
    private javax.swing.JTextField GUIOOIDJTextField3;
    private javax.swing.JTextField NONJTextField1;
    private javax.swing.JButton OKJButton1;
    private javax.swing.JTextField UserId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
