/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GetPositions.java
 *
 * Created on Aug 17, 2009, 11:02:27 AM
 */

package com.omnesys.testnestq.gui;

import com.omnesys.nestq.classes.SymbolData;

import java.util.Vector;

/**
 *
 * @author Pankaj
 */
public class GetPositions extends javax.swing.JFrame implements Runnable
{
   private SymbolData symboldata;
   private boolean flag;
  

    /** Creates new form GetPositions */
    public GetPositions() {
        init();
    }

    private void init() {
        flag= HomePage.nc.bUserEnable;
        System.out.println("flag-------------------"+flag);
        HomePage.listSymbols = new Vector();
        HomePage.listSymbols.add("Scrip Names");
        HomePage.listExchanges = new Vector();
        java.awt.EventQueue.invokeLater(this);
        initComponents();        
        HomePage.nc.GetAllExchanges(this,"JAPI");
    }

    public void initExchanges() {
        System.out.println("init exchanges called");

        if(HomePage.listExchanges != null &&
                HomePage.listExchanges.get(0) != null &&
                HomePage.listExchanges.get(0).toString().length() > 0)
        {
            jComboBoxExchange.removeAllItems();
            int nExch = HomePage.listExchanges.size();
            for(int i=0; i<nExch; i++)
            {
                jComboBoxExchange.addItem(HomePage.listExchanges.get(i));
                System.out.println(HomePage.listExchanges.get(i)+" item added");
            }
            HomePage.nc.GetAllSymbols(this, HomePage.listExchanges.get(0).toString(),"JAPI");
            jComboBoxExchange.repaint();
        }
    }

    public void initSymbols() {
        System.out.println("init symbols called in get positions");
        jComboBoxTrdSymbol.removeAllItems();

        int nScrips = HomePage.listSymbols.size();
        for(int i=0 ; i<nScrips; i++)
        {
            jComboBoxTrdSymbol.addItem(HomePage.listSymbols.get(i));
        }
        jComboBoxTrdSymbol.repaint();
    }

    public void run() {
        this.setVisible(true);
    }    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxExchange = new javax.swing.JComboBox();
        jComboBoxTrdSymbol = new javax.swing.JComboBox();
        jComboBoxProduct = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButtonGetPos = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldAccID = new javax.swing.JTextField();
        jLabelPositions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GetPositions");

        jComboBoxExchange.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxExchangeItemStateChanged(evt);
            }
        });

        jComboBoxTrdSymbol.setActionCommand("");

        jComboBoxProduct.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ARB", "NRML", "CNC", "MIS", "MLB" }));

        jLabel2.setText("Exchange         Trading Symbol                   Product                Account ID");

        jButtonGetPos.setText("Get Positions");
        jButtonGetPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetPosActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        if(!flag)
        {
            jTextFieldAccID.setText("NA");

            jTextFieldAccID.setEnabled(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPositions, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButtonGetPos)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonCancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxExchange, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxTrdSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAccID, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxExchange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTrdSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAccID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGetPos)
                    .addComponent(jButtonCancel))
                .addGap(26, 26, 26)
                .addComponent(jLabelPositions, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGetPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetPosActionPerformed
        System.out.println("get pos button pressed");
        String accID="";
        if(flag)
        accID = jTextFieldAccID.getText();
        else
        accID="SET";
        String exch  = jComboBoxExchange.getSelectedItem().toString();
        String symbol = jComboBoxTrdSymbol.getSelectedItem().toString();
        String product = jComboBoxProduct.getSelectedItem().toString();
     
        int index = jComboBoxTrdSymbol.getSelectedIndex();
        System.out.println("index"+index);
       
        if(index > 0 ){
           
            System.out.println(accID+" "+exch+" "+symbol+" "+product);
            SymbolData symboldata = (SymbolData)(HomePage.symbolData.get(index - 1));
            symbol = symboldata.sSymbol;
            if(product.equalsIgnoreCase("mlb"))
               product = "ML";
            System.out.println(accID+" "+exch+" "+symboldata.sSymbolName+" "+product);
            HomePage.nc.GetPositions(this, accID, exch, symbol, product,"JAPI");
        }
        else
        {
            
           HomePage.nc.GetPositions(this, accID, exch, symbol, product,"JAPI");
        }
    }//GEN-LAST:event_jButtonGetPosActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jComboBoxExchangeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxExchangeItemStateChanged
        String str = evt.getItem().toString();
        System.out.println(str);
      HomePage.nc.GetAllSymbols(this, str,"JAPI");
    }//GEN-LAST:event_jComboBoxExchangeItemStateChanged

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonGetPos;
    private javax.swing.JComboBox jComboBoxExchange;
    private javax.swing.JComboBox jComboBoxProduct;
    private javax.swing.JComboBox jComboBoxTrdSymbol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabelPositions;
    javax.swing.JTextField jTextFieldAccID;
    // End of variables declaration//GEN-END:variables


}
