/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrderBook.java
 *
 * Created on Jun 15, 2010, 12:22:20 PM
 */

package com.omnesys.testnestq.gui;
import com.omnesys.nestq.classes.OrderReport;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
/**
 *
 * @author srivatsa
 */
public class OrderBook extends javax.swing.JFrame implements Runnable{

    /** Creates new form OrderBook */

    Vector Order;

    public OrderBook() {
        java.awt.EventQueue.invokeLater(this);
        initComponents();
    }
    public OrderBook(Vector Order)
    {
        this.Order = Order;
        java.awt.EventQueue.invokeLater(this);
        initComponents();
        initTable();
    }
    public void initTable()
    {

        int nRows = Order.size();
         for(int i=0; i<nRows; i++)

         {
              OrderReport fr = (OrderReport)Order.get(i);
              int j = 0;
              // "AccountID", "Exchnage", "TradingSymbol", "Product", "PriceType", "NestOrderNumber", "Status", "Pricetofill", "QuantToFill", "OrderDuartion"
               jTable1.setValueAt(fr.sAccountId, i, j++);
                jTable1.setValueAt(fr.sExchSeg, i, j++);
                 jTable1.setValueAt(fr.sTradingSymbol, i, j++);
                  jTable1.setValueAt(fr.sProduct, i, j++);
                   jTable1.setValueAt(fr.sPriceType, i, j++);
                    jTable1.setValueAt(fr.sNestOrderNo, i, j++);
                     jTable1.setValueAt(fr.sStatus, i, j++);
                      jTable1.setValueAt(fr.iPriceToFill, i, j++);
                       jTable1.setValueAt(fr.iQtyToFill, i, j++);
                        jTable1.setValueAt(fr.sOrderDuration, i, j++);
                         jTable1.setValueAt(fr.sExchOrderId, i, j++);


                         jTable1.setValueAt(fr.sModifiedInfo, i, j++);
                         jTable1.setValueAt(fr.sCancelledInfo, i, j++);
                         jTable1.setValueAt(fr.sExchOrdUpdateTime, i, j++);
                         jTable1.setValueAt(fr.sExchTime, i, j++);
                         jTable1.setValueAt(fr.sValidDate, i, j++);
                          jTable1.setValueAt(fr.iSecSinceBOE, i, j++);
                          jTable1.setValueAt(fr.sReport, i, j++);

         }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Order Report ");
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        jScrollPane1.setAutoscrolls(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [Order.size()][41] ,
            new String [] {
                "AccountID", "Exchnage", "TradingSymbol", "Product", "PriceType", "NestOrderNumber", "Status", "Pricetofill", "QuantToFill", "OrderDuartion","ExchOrdId","Modified","Cancelled","ExOrderUpdateTime","ExchangeTime","OrderValidtyDte","NestOrderUpdateTime","Report"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(318, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void run() {
        this.setVisible(true);
    }

}
