/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TardeBook.java
 *
 * Created on Jun 11, 2010, 4:23:15 PM
 */

package com.omnesys.testnestq.gui;
import com.omnesys.nestq.classes.FillReport;
import com.omnesys.nestq.classes.PositionParams;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
/**
 *
 * @author srivatsa
 */
public class TradeBook extends javax.swing.JFrame implements Runnable {


     Vector Trade;
    /** Creates new form TardeBook */
    public TradeBook() {
          java.awt.EventQueue.invokeLater(this);
        initComponents();
    }
    public TradeBook(Vector Trade)
    {
        this.Trade = Trade;
        java.awt.EventQueue.invokeLater(this);
        initComponents();
        initTable();
    }
    public void initTable()
    {

        int nRows = Trade.size();
         for(int i=0; i<nRows; i++)

         {
              FillReport fr = (FillReport)Trade.get(i);
              int j = 0;
               if(fr.sExchSeg == null ||
               fr.sExchSeg.length() == 0)
                fr.sExchSeg = "NA";
            jTable1.setValueAt(fr.sExchSeg, i, j++);

            //nest order no  MNM_NEST_ORDER_NUMBER
            if(fr.sNestOrdNum == null ||
               fr.sNestOrdNum.length() == 0)
                fr.sNestOrdNum = "NA";
            jTable1.setValueAt(fr.sNestOrdNum, i, j++);

            //Transaction type (buy/cell) MNM_TRANSACTION_TYPE
            jTable1.setValueAt(fr.sTransType, i, j++);

            //symbol  MNM_SYMBOL
            jTable1.setValueAt(fr.sSymbol, i, j++);

            //Trade price  MNM_FILL_PRICE
           //double d1=Double.parseDouble(fr.dFillPrice);
           // d1/=100;
            jTable1.setValueAt((fr.dFillPrice), i, j++);


            //trade qty    MNM_FILL_SIZE
            jTable1.setValueAt((fr.lFillSize), i, j++);

            //account ID   MNM_ACCOUNT_ID
            jTable1.setValueAt(fr.sAccountId, i, j++);

            //customer firm  MNM_CUSTOMER_FIRM
            jTable1.setValueAt(fr.sCustomerFirm, i, j++);

            //Trading symbol MNM_TRADING_SYMBOL
            jTable1.setValueAt(fr.sTrdSymbol, i, j++);

            //exchange order ID   MNM_EXCH_ORD_ID
            jTable1.setValueAt(fr.sExchOrdId, i, j++);

            //status  MNM_STATUS
            jTable1.setValueAt(fr.sStatus, i, j++);

            //exchange time MNM_EXCHANGE_TIME
            jTable1.setValueAt(fr.sExchTime, i, j++);

            //trade date    MNM_FILL_DATE
            jTable1.setValueAt(fr.sFillDate, i, j++);

            //trade ID      MNM_FILL_ID
            jTable1.setValueAt(fr.sFillId, i, j++);

            //trade time    MNM_FILL_TIME
            jTable1.setValueAt(fr.sFillTime, i, j++);

            //Gui Order ID  MNM_GUI_ORDER_ID
            jTable1.setValueAt(fr.sGuiOrdId, i, j++);

            //Gui Original order ID  MNM_GUI_ORIGINAL_ORDER_ID
            jTable1.setValueAt(fr.sGuiOrgOrdId, i, j++);

            //product type   MNM_PRODUCT
            jTable1.setValueAt(fr.sProduct, i, j++);

            //report type    MNM_REPORT_TYPE
            jTable1.setValueAt(fr.sReportType, i, j++);

            //stretegy code  MNM_STRATEGY_CODE
            jTable1.setValueAt(fr.sStrategyCode, i, j++);

            //warehouse location MNM_WAREHOUSE_LOCATION
            jTable1.setValueAt(fr.sWarehouseLoc, i, j++);

            //iquantofill  MNM_QUAN_TO_FILL
            jTable1.setValueAt(fr.iQtyToFill, i, j++);
           // IFILLEDSHARES MNM_FILLED_SHARES
            jTable1.setValueAt(fr.iFillShare, i, j++);

           //orderDuration
             jTable1.setValueAt(fr.sOrderDuartion, i, j++);

             //reqid
             jTable1.setValueAt(fr.sReqId, i, j++);

             //Price Type
             jTable1.setValueAt(fr.sPriceType, i, j++);

             //
               jTable1.setValueAt(fr.shFillLeg, i, j++);

               //USER
               jTable1.setValueAt(fr.sUserId, i, j++);

               //BROKER
               jTable1.setValueAt(fr.sBroker, i, j++);
               //BRANCH
               jTable1.setValueAt(fr.sBranchId, i, j++);

         }
    }
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TradeBook");
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [Trade.size()][41]

            ,
            new String [] {
                "Exch Seg", "Nest Order No", "Buy/Sell", "Symbol Name", "Trade Price", "Trade Qty", "Account ID", "Customer Firm", "Trading Symbol", "ExchOrderID", "Status", "Exchange Time", "Trade Date", "Trade ID", "Trade Time", "GUI Order ID", "GuiOrgOrdID", "Product", "Report", "Stretegy Code", "Warehouse Info","Quant2Fill","Filled Shares","OrderDuartion","ReqId","PriceType","Fill Leg","User","Broker","Branch"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("PositionConvrt");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MIS", "CNC" }));
        jComboBox1.setName("jComboBox1"); // NOI18N

        jLabel2.setText("");
        jLabel2.setName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

         int row            = jTable1.getSelectedRow();
          if(row == -1)
        {
            ;//JOptionPane.showMessageDialog(null, "Please select an order","", JOptionPane.INFORMATION_MESSAGE);
        }
          else
          { PositionParams pr=new PositionParams();
              TableColumn column = jTable1.getColumn("Exch Seg");
              pr.sExchSeg      = (String)jTable1.getValueAt(row, column.getModelIndex());
               
                column = jTable1.getColumn("Nest Order No");
                pr.sNestOrderNo        = (String)jTable1.getValueAt(row, column.getModelIndex());
                column = jTable1.getColumn("Buy/Sell");
                pr.sTransactionType       = (String)jTable1.getValueAt(row, column.getModelIndex());
                column = jTable1.getColumn("Symbol Name");
                pr.sSymbol       = (String)jTable1.getValueAt(row, column.getModelIndex());
                column = jTable1.getColumn("Trade Price");
                pr.dPriceToFill       = (String)jTable1.getValueAt(row, column.getModelIndex());
                column = jTable1.getColumn("Trade Qty");
                pr.iFillQty        = (String)jTable1.getValueAt(row, column.getModelIndex());
                column = jTable1.getColumn("Account ID");
                pr.sAccountId        = (String)jTable1.getValueAt(row, column.getModelIndex());
                column = jTable1.getColumn("Customer Firm");
                pr.sCustomerOrFirm       = (String)jTable1.getValueAt(row, column.getModelIndex());
               
              
                column = jTable1.getColumn("Status");
                pr.sStatus       = (String)jTable1.getValueAt(row, column.getModelIndex());
               
                column = jTable1.getColumn("Trade Date");
                pr.sFillDate        = (String)jTable1.getValueAt(row, column.getModelIndex());
                column = jTable1.getColumn("Trade ID");
                pr.sFillId       = (String)jTable1.getValueAt(row, column.getModelIndex());
                column = jTable1.getColumn("Trade Time");
                pr.sFillTime        = (String)jTable1.getValueAt(row, column.getModelIndex());
               
                column = jTable1.getColumn("Product");
                pr.sProductCode      = (String)jTable1.getValueAt(row, column.getModelIndex());
               
                
                column = jTable1.getColumn("Quant2Fill");
                pr.iQtyToFill        = (String)jTable1.getValueAt(row, column.getModelIndex());
                column = jTable1.getColumn("Filled Shares");
                pr.iFilledShares        = (String)jTable1.getValueAt(row, column.getModelIndex());
                column = jTable1.getColumn("OrderDuartion");
                pr.sOrderDuration        = (String)jTable1.getValueAt(row, column.getModelIndex());



                column = jTable1.getColumn("ReqId");
                pr.sNestOrderReqId       = (String)jTable1.getValueAt(row, column.getModelIndex());
                 column = jTable1.getColumn("PriceType");
                pr.sPriceType       = (String)jTable1.getValueAt(row, column.getModelIndex());
                 column = jTable1.getColumn("Fill Leg");
                pr.iFillLeg        = (String)jTable1.getValueAt(row, column.getModelIndex());
                 column = jTable1.getColumn("User");
                pr.sUser        = (String)jTable1.getValueAt(row, column.getModelIndex());
                column = jTable1.getColumn("Broker");
                pr.sBroker        = (String)jTable1.getValueAt(row, column.getModelIndex());
                column = jTable1.getColumn("Branch");
                pr.sBranchId        = (String)jTable1.getValueAt(row, column.getModelIndex());

                pr.sProductChge = jComboBox1.getSelectedItem().toString();
               

                  column = jTable1.getColumn("Trading Symbol");
                pr.sTradingSymbol        = (String)jTable1.getValueAt(row, column.getModelIndex());
                HomePage.nc.PositionConvrt(this, pr, "JAPI");




          }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
     public void run() {
                this.setVisible(true);
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
