/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GetClients.java
 *
 * Created on Jun 29, 2010, 12:02:20 PM
 */

package com.omnesys.testnestq.gui;

import com.omnesys.nestq.classes.Clients;
import java.util.Vector;

/**
 *
 * @author srivatsa
 */
public class GetClients extends javax.swing.JFrame implements Runnable {

    /** Creates new form GetClients */
    Vector getClients;
    public GetClients() {
        java.awt.EventQueue.invokeLater(this);
        initComponents();
    }
    public GetClients(Vector getClients) {
        this.getClients=getClients;
         java.awt.EventQueue.invokeLater(this);
        initComponents();
        initTable();
    }
     public void initTable()

     {
         int rows=getClients.size();
         System.out.println("rows"+rows);
          for(int i=0;i<rows;i++)
          {
               Clients pr=(Clients)getClients.get(i);
                int j = 0;


                jTable1.setValueAt(pr.AccountId,i,j++);
            //net qty
                         jTable1.setValueAt(pr.AccountName,i,j++);
            //net ammount
                            jTable1.setValueAt(pr.AccountType,i,j++);
          }
     }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("GET CLIENTS");
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [getClients.size()][10]

            ,
            new String [] {
                "ACC ID", "AccN", "AccType"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void run() {
         this.setVisible(true);
    }

}
