/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GetLimits.java
 *
 * Created on May 27, 2010, 12:24:42 PM
 */

package com.omnesys.testnestq.gui;

import com.omnesys.nestq.classes.NestControl;

/**
 *
 * @author srivatsa
 */
public class GetLimits extends javax.swing.JFrame implements Runnable{

    /** Creates new form GetLimits */
    private NestControl nc;
    private boolean flag;
    public GetLimits() {
          flag= HomePage.nc.bUserEnable;
         nc = HomePage.nc;
        java.awt.EventQueue.invokeLater(this);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelLedger = new javax.swing.JLabel();
        jLabelBooked = new javax.swing.JLabel();
        jLabelNotional = new javax.swing.JLabel();
        jLabelMargin = new javax.swing.JLabel();
        jLabelPayin = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ACCOUNT ID");
        jLabel1.setName("jLabel1"); // NOI18N

        if(!flag)
        {
            jTextField1.setText("");
            jTextField1.setName("jTextField1"); // NOI18N
        }
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("GetLimits");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelLedger.setText("");
        jLabelLedger.setName("jLabelLedger"); // NOI18N

        jLabelBooked.setText("");
        jLabelBooked.setName("jLabelBooked"); // NOI18N

        jLabelNotional.setText("");
        jLabelNotional.setName("jLabelNotional"); // NOI18N

        jLabelMargin.setText("");
        jLabelMargin.setName("jLabelMargin"); // NOI18N

        jLabelPayin.setText("");
        jLabelPayin.setName("jLabelPayin"); // NOI18N

        jButton2.setText("OK");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLedger)
                            .addComponent(jLabelBooked)
                            .addComponent(jLabelNotional)
                            .addComponent(jLabelMargin)
                            .addComponent(jLabelPayin)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(19, 19, 19)
                .addComponent(jLabelLedger)
                .addGap(18, 18, 18)
                .addComponent(jLabelBooked)
                .addGap(33, 33, 33)
                .addComponent(jLabelNotional)
                .addGap(27, 27, 27)
                .addComponent(jLabelMargin)
                .addGap(36, 36, 36)
                .addComponent(jLabelPayin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("Limits Button clicked");
      String AccountId="";
         if(flag)
         AccountId=jTextField1.getText();
         else
            AccountId="SET";

        String sUserMsg=jTextField1.getText();
        System.out.println("AccountId"+AccountId);
        HomePage.nc.GetLimits(this,AccountId,sUserMsg);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    

    public void run() {
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelBooked;
    public javax.swing.JLabel jLabelLedger;
    public javax.swing.JLabel jLabelMargin;
    public javax.swing.JLabel jLabelNotional;
    public javax.swing.JLabel jLabelPayin;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
