/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModifyOrderPage.java
 *
 * Created on Jul 7, 2009, 6:17:15 PM
 */

package com.omnesys.testnestq.gui;

import com.omnesys.nestq.classes.ModOrderParams;
import com.omnesys.nestq.classes.NestControl;

/**
 *
 * @author Pankaj
 */
public class ModifyOrderPage extends javax.swing.JFrame implements Runnable
{
    private NestControl nc;
    private ModOrderParams orderParams;
    


    /** Creates new form ModifyOrderPage */
    public ModifyOrderPage()
    {
        nc = HomePage.nc;
        orderParams = new ModOrderParams();
        System.out.println("before initcom");
        initComponents();
        System.out.println("after initcom");
    }

    public ModifyOrderPage(String nestOrdNum, String sGuiOrdId, String sGuiOrgOrdId,
                           String Exch, String transType, String scripName,
                           String customerFirm, String ProdType, String AccID,String sUserId)
    {
        this();
        orderParams.sNestOrdNum  = nestOrdNum;
        orderParams.sGuiOrdId    = sGuiOrdId;
        orderParams.sGuiOrgOrdId = sGuiOrgOrdId;
        System.out.println("another cons");
        ExchJComboBox1.removeAllItems();
        ExchJComboBox1.addItem(Exch);

        BSJComboBox2.removeAllItems();
        if(transType.equalsIgnoreCase("B"))
            BSJComboBox2.addItem("Buy");
        else BSJComboBox2.addItem("Sell");

        ScripNameJComboBox4.removeAllItems();
        ScripNameJComboBox4.addItem(scripName);

        CustomerFirmJComboBox6.removeAllItems();
        CustomerFirmJComboBox6.addItem(customerFirm);

        ProductJComboBox5.removeAllItems();
        ProductJComboBox5.addItem(ProdType);
        AccIDJTextField4.setText(AccID);
        UserId.setText(sUserId);
        java.awt.EventQueue.invokeLater(this);
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        QtyJTextField1 = new javax.swing.JTextField();
        DisQtyJTextField1 = new javax.swing.JTextField();
        OrderPriceJTextField2 = new javax.swing.JTextField();
        TrigPriceJTextField3 = new javax.swing.JTextField();
        AccIDJTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ExchJComboBox1 = new javax.swing.JComboBox();
        BSJComboBox2 = new javax.swing.JComboBox();
        OrdTypeJComboBox3 = new javax.swing.JComboBox();
        ScripNameJComboBox4 = new javax.swing.JComboBox();
        CustomerFirmJComboBox6 = new javax.swing.JComboBox();
        ProductJComboBox5 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ValidityJComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTValidDate1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        UserId = new javax.swing.JTextField();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setForeground(new java.awt.Color(204, 0, 51));

        jLabel3.setText("Exch Seg  Buy/Sell        Order Type           Scrip Name       Cutomer Firm     Product Type     Validity");

        QtyJTextField1.setText("0");

        DisQtyJTextField1.setText("0");

        OrderPriceJTextField2.setText("0.0");
        OrderPriceJTextField2.setEnabled(false);

        TrigPriceJTextField3.setText("0.0");
        TrigPriceJTextField3.setEnabled(false);

        AccIDJTextField4.setEditable(false);
        AccIDJTextField4.setEnabled(false);

        jLabel4.setText("Quantity          Disclosed Qty    Order Price   Trigger Price    Account ID");

        ExchJComboBox1.setEnabled(false);

        BSJComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buy", "Sell" }));
        BSJComboBox2.setEnabled(false);

        OrdTypeJComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Market Order", "Limit Order", "SL", "SL-M" }));
        OrdTypeJComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OrdTypeJComboBox3ItemStateChanged(evt);
            }
        });

        ScripNameJComboBox4.setEnabled(false);

        CustomerFirmJComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "firm" }));
        CustomerFirmJComboBox6.setEnabled(false);

        ProductJComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "product" }));
        ProductJComboBox5.setActionCommand("");
        ProductJComboBox5.setEnabled(false);

        jButton1.setText("Modify Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel1.setText("Modify Order");

        ValidityJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DAY", "IOC","GTC" }));

        jLabel6.setText("gtdDate");

        jTValidDate1.setText("");

        jLabel7.setText("UserId");

        UserId.setEditable(false);
        UserId.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(344, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(QtyJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DisQtyJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderPriceJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TrigPriceJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AccIDJTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTValidDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(256, 256, 256))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ExchJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BSJComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(OrdTypeJComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ScripNameJComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(CustomerFirmJComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ProductJComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ValidityJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(UserId, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExchJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BSJComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrdTypeJComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScripNameJComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductJComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerFirmJComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValidityJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QtyJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisQtyJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderPriceJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TrigPriceJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccIDJTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTValidDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OrdTypeJComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OrdTypeJComboBox3ItemStateChanged
        String itemSelected = ((String)OrdTypeJComboBox3.getSelectedItem()).trim();
        if(itemSelected.equalsIgnoreCase("Market Order")) {
            OrderPriceJTextField2.disable();
            TrigPriceJTextField3.disable();
        } else if(itemSelected.equalsIgnoreCase("limit order") || itemSelected.equalsIgnoreCase("au")) {
            OrderPriceJTextField2.enable();
            TrigPriceJTextField3.disable();
        } else if(itemSelected.equalsIgnoreCase("sl")) {
            OrdTypeJComboBox3.enable();
            TrigPriceJTextField3.enable();
        } else if(itemSelected.equalsIgnoreCase("sl-m")) {
            OrderPriceJTextField2.disable();
            TrigPriceJTextField3.enable();
        }
        OrderPriceJTextField2.repaint();
        TrigPriceJTextField3.repaint();
}//GEN-LAST:event_OrdTypeJComboBox3ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            boolean flag = false;           

           // orderParams.sUserId=AccIDJTextField4.getText();

           //System.out.println("orderParams.sUserId"+orderParams.sUserId);


            orderParams.sOrderType = ((String)OrdTypeJComboBox3.getSelectedItem()).trim();
            if(orderParams.sOrderType.equalsIgnoreCase("Market Order"))
                orderParams.sOrderType = "MKT";
            else if(orderParams.sOrderType.equalsIgnoreCase("Limit Order"))
                orderParams.sOrderType = "L";

            if(QtyJTextField1.getText() == null ||
                    QtyJTextField1.getText().length() == 0) {
                QtyJTextField1.setText("0");
            }
            orderParams.lQuantity = Long.parseLong(QtyJTextField1.getText());
            if(orderParams.lQuantity <= 0)
                flag = true;

            if(DisQtyJTextField1.getText() == null ||
                    DisQtyJTextField1.getText().length() == 0) {
                DisQtyJTextField1.setText("0");
            }
            orderParams.lDiscQuantity = Long.parseLong(DisQtyJTextField1.getText());
            if(orderParams.lDiscQuantity < 0)
                flag = true;

            if(OrderPriceJTextField2.getText() == null ||
                    OrderPriceJTextField2.getText().length() == 0) {
                OrderPriceJTextField2.setText("0.0");
            }
            orderParams.dPrice = 100*Double.parseDouble(OrderPriceJTextField2.getText());
            if((orderParams.sOrderType.equalsIgnoreCase("L") ||
                    orderParams.sOrderType.equalsIgnoreCase("SL")) &&
                    orderParams.dPrice <= 0)
                flag = true;
                        
            if(TrigPriceJTextField3.getText()== null ||
                    TrigPriceJTextField3.getText().length() == 0) {
                TrigPriceJTextField3.setText("0.0");
            }
            orderParams.dTriggerPrice = 100*Double.parseDouble(TrigPriceJTextField3.getText());
            System.out.println("orderParams.dTriggerPrice"+orderParams.dTriggerPrice);
            if((orderParams.sOrderType.equalsIgnoreCase("SL")||
                    orderParams.sOrderType.equalsIgnoreCase("SL-M")) &&
                    orderParams.dTriggerPrice < 0) {
                flag = true;
            }
            orderParams.sOrdDuration = (String)ValidityJComboBox.getSelectedItem();
            orderParams.sValidDate=(String)jTValidDate1.getText();
            orderParams.sUserId=(String)UserId.getText();
            System.out.println("orderParams.sUserId"+orderParams.sUserId);

            if(flag) {
                jLabel4.setText("All data fields must be filled");
            } else {
                //placing order
                System.out.println("Placing order:");
                nc.ModifyOrder(this, orderParams);
                this.dispose();
            }

        }catch(Exception e) {
            System.out.println("Wrong data when placing order");
            e.printStackTrace();
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //        this.dispose();
        this.setVisible(false);
}//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyOrderPage().setVisible(true);
            }
        });
    }*/

    public void run()
    {
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField AccIDJTextField4;
    javax.swing.JComboBox BSJComboBox2;
    javax.swing.JComboBox CustomerFirmJComboBox6;
    private javax.swing.JTextField DisQtyJTextField1;
    javax.swing.JComboBox ExchJComboBox1;
    javax.swing.JComboBox OrdTypeJComboBox3;
    javax.swing.JTextField OrderPriceJTextField2;
    javax.swing.JComboBox ProductJComboBox5;
    javax.swing.JTextField QtyJTextField1;
    javax.swing.JComboBox ScripNameJComboBox4;
    javax.swing.JTextField TrigPriceJTextField3;
    private javax.swing.JTextField UserId;
    private javax.swing.JComboBox ValidityJComboBox;
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTValidDate1;
    // End of variables declaration//GEN-END:variables

}
