/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PositionBook.java
 *
 * Created on Jun 5, 2010, 11:03:23 AM
 */

package com.omnesys.testnestq.gui;
import com.omnesys.nestq.classes.PosData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
/**
 *
 * @author srivatsa
 */
public class PositionBook extends javax.swing.JFrame implements Runnable{

    /** Creates new form PositionBook */
    Vector positionshistory;
    public PositionBook() {
        java.awt.EventQueue.invokeLater(this);
        initComponents();
    }
    public PositionBook(Vector positionshistory)
    {
        this.positionshistory=positionshistory;
        java.awt.EventQueue.invokeLater(this);
        initComponents();
        initTable();

    }
    public void initTable()
    {

        int nrows=positionshistory.size();
        System.out.println("nrows-----------"+nrows);
        for(int i=0;i<nrows;i++)
        {
            PosData pr=(PosData)positionshistory.get(i);
            System.out.println("pr.sExchSeg"+pr.sExchSeg);
            int j = 0;

             System.out.println("pr.sAccId"+pr.sAccId);
              System.out.println("pr.sProduct"+pr.sProduct);

            jTable1.setValueAt(pr.sExchSeg, i, j++);
            // accountid
            jTable1.setValueAt(pr.sAccId, i, j++);
            // product
            jTable1.setValueAt(pr.sProduct,i,j++);
            // symbol
            jTable1.setValueAt(pr.sSymbol,i,j++);
            //buy qty
              jTable1.setValueAt(pr.sFillBuyAmount,i,j++);
            //avg price
                jTable1.setValueAt(pr.iFillBuyQty,i,j++);
            //buy price
                 jTable1.setValueAt(pr.sFillSellAmount,i,j++);
            //sell qty
                    jTable1.setValueAt(pr.iFillSellQty,i,j++);
            //avg sell price
                      jTable1.setValueAt(pr.sFillBuy_CF_Amount,i,j++);
            //sell price
                        jTable1.setValueAt(pr.iFillBuy_CF_Qty,i,j++);
            //net qty
                         jTable1.setValueAt(pr.sFillSell_CF_Amount,i,j++);
            //net ammount
                            jTable1.setValueAt(pr.iFillSell_CF_Qty,i,j++);

        
    }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("POSITIONS");
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [positionshistory.size()][21] ,
            new String [] {
                "Exchnage", "accountif", "Produc", "Symbol","BuyPrice","BuyQty","SellPrice","SellQty","CFBuyPrice","CFBuyQty","CFSellPrice","CFSellQty"
            }
        ){
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Cancel");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void run() {
      this.setVisible(true);
    }

}
