/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TradeHistoryPage.java
 *
 * Created on Jul 3, 2009, 1:38:16 PM
 */

package com.omnesys.testnestq.gui;

import com.omnesys.nestq.classes.FillReport;
import com.omnesys.nestq.classes.PositionParams;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author Pankaj
 */
public class TradeHistoryPage extends javax.swing.JFrame implements Runnable
{
    Vector fillReport;
    /** Creates new form TradeHistoryPage */
    public TradeHistoryPage() {
         java.awt.EventQueue.invokeLater(this);
        initComponents();
    }

    public TradeHistoryPage(Vector fillReport)
    {
        this.fillReport = fillReport;
        java.awt.EventQueue.invokeLater(this);
        initComponents();
        initTable();
    }

    public void initTable()
    {
        int nRows = fillReport.size();

        for(int i=0; i<nRows; i++)
        {
            FillReport fr = (FillReport)fillReport.get(i);
            int j = 0;
            //exch seg  MNM_EXCH_SEG
            if(fr.sExchSeg == null ||
               fr.sExchSeg.length() == 0)
                fr.sExchSeg = "NA";
            jTable1.setValueAt(fr.sExchSeg, i, j++);

            //nest order no  MNM_NEST_ORDER_NUMBER
            if(fr.sNestOrdNum == null ||
               fr.sNestOrdNum.length() == 0)
                fr.sNestOrdNum = "NA";
            jTable1.setValueAt(fr.sNestOrdNum, i, j++);

            //Transaction type (buy/cell) MNM_TRANSACTION_TYPE
            jTable1.setValueAt(fr.sTransType, i, j++);

            //symbol  MNM_SYMBOL
            jTable1.setValueAt(fr.sSymbol, i, j++);           
            
            //Trade price  MNM_FILL_PRICE
            double d1=Double.parseDouble(fr.dFillPrice);
            d1/=100;
            jTable1.setValueAt((d1), i, j++);

            //trade qty    MNM_FILL_SIZE
            jTable1.setValueAt((fr.lFillSize), i, j++);

            //account ID   MNM_ACCOUNT_ID
            jTable1.setValueAt(fr.sAccountId, i, j++);

            //customer firm  MNM_CUSTOMER_FIRM
            jTable1.setValueAt(fr.sCustomerFirm, i, j++);
            
            //Trading symbol MNM_TRADING_SYMBOL
            jTable1.setValueAt(fr.sTrdSymbol, i, j++);

            //exchange order ID   MNM_EXCH_ORD_ID
            jTable1.setValueAt(fr.sExchOrdId, i, j++);

            //status  MNM_STATUS
            jTable1.setValueAt(fr.sStatus, i, j++);

            //exchange time MNM_EXCHANGE_TIME
            jTable1.setValueAt(fr.sExchTime, i, j++);

            //trade date    MNM_FILL_DATE
            jTable1.setValueAt(fr.sFillDate, i, j++);

            //trade ID      MNM_FILL_ID
            jTable1.setValueAt(fr.sFillId, i, j++);

            //trade time    MNM_FILL_TIME
            jTable1.setValueAt(fr.sFillTime, i, j++);

            //Gui Order ID  MNM_GUI_ORDER_ID
            jTable1.setValueAt(fr.sGuiOrdId, i, j++);

            //Gui Original order ID  MNM_GUI_ORIGINAL_ORDER_ID
            jTable1.setValueAt(fr.sGuiOrgOrdId, i, j++);

            //product type   MNM_PRODUCT
            jTable1.setValueAt(fr.sProduct, i, j++);

            //report type    MNM_REPORT_TYPE
            jTable1.setValueAt(fr.sReportType, i, j++);            

            //stretegy code  MNM_STRATEGY_CODE
            jTable1.setValueAt(fr.sStrategyCode, i, j++);           

            //warehouse location MNM_WAREHOUSE_LOCATION
            jTable1.setValueAt(fr.sWarehouseLoc, i, j++);

            //iquantofill  MNM_QUAN_TO_FILL
            jTable1.setValueAt(fr.iQtyToFill, i, j++);
           // IFILLEDSHARES MNM_FILLED_SHARES
            jTable1.setValueAt(fr.iFillShare, i, j++);

           //orderDuration
             jTable1.setValueAt(fr.sOrderDuartion, i, j++);

             //reqid
             jTable1.setValueAt(fr.sReqId, i, j++);

             //Price Type
             jTable1.setValueAt(fr.sPriceType, i, j++);

             //
               jTable1.setValueAt(fr.shFillLeg, i, j++);

               //USER
               jTable1.setValueAt(fr.sUserId, i, j++);

               //BROKER
               jTable1.setValueAt(fr.sBroker, i, j++);
               //BRANCH
               jTable1.setValueAt(fr.sBranchId, i, j++);

        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Trade History");

        jButton1.setText("Close Window");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(454, 420));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [fillReport.size()][21],
            new String [] {
                "Exch Seg", "Nest Order No", "Buy/Sell", "Symbol Name", "Trade Price", "Trade Qty", "Account ID", "Customer Firm", "Trading Symbol", "ExchOrderID", "Status", "Exchange Time", "Trade Date", "Trade ID", "Trade Time", "GUI Order ID", "GuiOrgOrdID", "Product", "Report", "Stretegy Code", "Warehouse Info","Quant2Fill","Filled Shares","OrderDuartion","ReqId","PriceType","Fill Leg","User","Broker","Branch"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

   

    public void run() {
                this.setVisible(true);
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
